/// Flutter icons SecuremeApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SecuremeApp
///      fonts:
///       - asset: fonts/SecuremeApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SecuremeApp {
  SecuremeApp._();

  static const _kFontFam = 'SecuremeApp';
  static const String? _kFontPkg = null;

  static const IconData general_settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
