/// Flutter icons Smartlets
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Smartlets
///      fonts:
///       - asset: fonts/Smartlets.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Smartlets {
  Smartlets._();

  static const _kFontFam = 'Smartlets';
  static const _kFontPkg = null;

  static const IconData bell_outlined = IconData(0xe800,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData bell_filled = IconData(0xe801,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData bookmark_outline = IconData(0xe802,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData compass = IconData(0xe803,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData bookmark = IconData(0xe804,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData compass_outline = IconData(0xe805,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData group_users_outlined = IconData(0xe807,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData kids_filled = IconData(0xe808,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData kids_outlined = IconData(0xe809,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData group_users_filled = IconData(0xe80a,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData kids = IconData(0xe80b,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData search = IconData(0xe80c,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData silverware = IconData(0xe80d,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData account = IconData(0xe80e,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData account_outline = IconData(0xe80f,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData pay_outlined_1 = IconData(0xe810,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData pay_filled = IconData(0xe813,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData pay_outlined = IconData(0xe814,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData user_outlined = IconData(0xe815,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData user_filled = IconData(0xe816,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData check_all = IconData(0xe817,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData game_pad_filled = IconData(0xe818,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData game_pad_outlined = IconData(0xe819,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData home_filled = IconData(0xe81a,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData home_outlined = IconData(0xe81b,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData book_filled = IconData(0xe81c,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData book_outlined = IconData(0xe81d,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData book_stack_filled = IconData(0xe81e,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData clock_icon = IconData(0xe837,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData lesson_icon = IconData(0xe838,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData play_icon = IconData(0xe839,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData user_icon = IconData(0xe83a,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData play_button = IconData(0xe842,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData skip_button = IconData(0xe843,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData pause_button = IconData(0xe844,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData fit_screen_icon = IconData(0xe849,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData low_volume = IconData(0xe84a,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData mute_volume = IconData(0xe84b,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData notification = IconData(0xe87b,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData project_idea = IconData(0xe8a8,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData star_award = IconData(0xe8a9,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
  static const IconData trophy = IconData(0xe8aa,
      fontFamily: _kFontFam, fontPackage: _kFontPkg as String?);
}
